project_name: myProject

infrastructure:
  database:
    type: mongo
    image: mongo:7-jammy
    data_volume: true
  
  cache:
    type: redis
    image: redis:7

services:
  api:
    type: node
    image: node:18
    port: 3000
    build_command: |
      npm install --legacy-peer-deps
      npm run build
    env:
      NODE_ENV: production
      PORT: 3000
    health_check:
      path: /health
      timeout: 30
