FROM jenkins/inbound-agent

USER root

RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    python3-venv \
    curl \
    git \
    ca-certificates \
    && rm -rf /var/lib/apt/lists/*

RUN pip3 install --no-cache-dir --break-system-packages \
    pyyaml \
    requests \
    docker \
    python-dotenv \
    jenkinsapi

RUN groupadd -f docker && usermod -aG docker jenkins

RUN curl -fsSL https://get.docker.com -o get-docker.sh \
    && sh get-docker.sh --no-start-container

COPY resources/python/requirements.txt /tmp/requirements.txt
RUN pip3 install --no-cache-dir -r /tmp/requirements.txt

# TEST FOR DOCKER INSTALLATIO
RUN docker --version

USER jenkins
WORKDIR /home/jenkins

#agent rebuild cheatsheet: (run in repo root folder)
#docker build -f Dockerfile.agent -t python-agent:latest . && docker tag python-agent:latest localhost:5000/python-agent:latest && docker push localhost:5000/python-agent:latest